name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: Assignment13/Chen_Zoey_ui_garden_build_checks

      - name: Run ESLint
        run: npm run lint
        working-directory: Assignment13/Chen_Zoey_ui_garden_build_checks

      - name: Run Prettier
        run: npm run format
        working-directory: Assignment13/Chen_Zoey_ui_garden_build_checks

      - name: Run Tests
        run: npm test -- --watchAll=false
        working-directory: Assignment13/Chen_Zoey_ui_garden_build_checks