name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: HUSKY_SKIP_INSTALL=1 npm install
        working-directory: Assignment13/Chen_Zoey_ui_garden_build_checks

      - name: Run ESLint
        run: npm run lint
        working-directory: Assignment13/Chen_Zoey_ui_garden_build_checks

      - name: Run Prettier
        run: npm run format
        working-directory: Assignment13/Chen_Zoey_ui_garden_build_checks

      - name: Run Tests
        run: npm test -- --watchAll=false
        working-directory: Assignment13/Chen_Zoey_ui_garden_build_checks